/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threadrelay;

/**
 *
 * @author martinelli.alessandr
 */
public class JFrmStaffetta extends javax.swing.JFrame {

    /**
     * Creates new form JFrmStaffetta
     */
    public JFrmStaffetta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pgbRunner3 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        pgbRunner2 = new javax.swing.JProgressBar();
        pgbRunner4 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        pgbRunner1 = new javax.swing.JProgressBar();
        cmbVelocita = new javax.swing.JComboBox<>();
        btnAvvia = new javax.swing.JButton();
        btnSospende = new javax.swing.JButton();
        btnFerma = new javax.swing.JButton();
        btnRiprendi = new javax.swing.JButton();
        pnlRunner1 = new javax.swing.JPanel();
        lblRunner1 = new javax.swing.JLabel();
        lblTempo1 = new javax.swing.JLabel();
        pnlRunner3 = new javax.swing.JPanel();
        lblRunner3 = new javax.swing.JLabel();
        lblTempo3 = new javax.swing.JLabel();
        pnlRunner4 = new javax.swing.JPanel();
        lblRunner4 = new javax.swing.JLabel();
        lblTempo4 = new javax.swing.JLabel();
        pnlRunner2 = new javax.swing.JPanel();
        lblRunner2 = new javax.swing.JLabel();
        lblTempo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBase.setLayout(null);

        jLabel3.setText("jLabel3");
        pnlBase.add(jLabel3);
        jLabel3.setBounds(20, 150, 37, 16);
        pnlBase.add(pgbRunner3);
        pgbRunner3.setBounds(6, 128, 379, 55);

        jLabel2.setText("jLabel2");
        pnlBase.add(jLabel2);
        jLabel2.setBounds(20, 90, 37, 16);
        pnlBase.add(pgbRunner2);
        pgbRunner2.setBounds(6, 67, 379, 55);
        pnlBase.add(pgbRunner4);
        pgbRunner4.setBounds(6, 189, 379, 55);

        jLabel1.setText("jLabel1");
        pnlBase.add(jLabel1);
        jLabel1.setBounds(20, 20, 37, 16);

        pgbRunner1.setBackground(new java.awt.Color(204, 204, 204));
        pnlBase.add(pgbRunner1);
        pgbRunner1.setBounds(6, 6, 379, 55);

        cmbVelocita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlBase.add(cmbVelocita);
        cmbVelocita.setBounds(12, 250, 72, 22);

        btnAvvia.setText("Avvia");
        pnlBase.add(btnAvvia);
        btnAvvia.setBounds(90, 250, 59, 22);

        btnSospende.setText("Sospendi");
        pnlBase.add(btnSospende);
        btnSospende.setBounds(161, 250, 78, 22);

        btnFerma.setText("Ferma");
        pnlBase.add(btnFerma);
        btnFerma.setBounds(245, 250, 63, 22);

        btnRiprendi.setText("Riprendi");
        pnlBase.add(btnRiprendi);
        btnRiprendi.setBounds(320, 250, 74, 22);

        pnlRunner1.setBackground(new java.awt.Color(153, 204, 255));

        lblRunner1.setText("Runner 1");

        lblTempo1.setText("0");

        javax.swing.GroupLayout pnlRunner1Layout = new javax.swing.GroupLayout(pnlRunner1);
        pnlRunner1.setLayout(pnlRunner1Layout);
        pnlRunner1Layout.setHorizontalGroup(
            pnlRunner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunner1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunner1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(lblTempo1)
                .addContainerGap())
        );
        pnlRunner1Layout.setVerticalGroup(
            pnlRunner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRunner1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRunner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunner1)
                    .addComponent(lblTempo1))
                .addGap(19, 19, 19))
        );

        pnlBase.add(pnlRunner1);
        pnlRunner1.setBounds(397, 6, 122, 55);

        pnlRunner3.setBackground(new java.awt.Color(153, 204, 255));

        lblRunner3.setText("Runner 3");

        lblTempo3.setText("0");

        javax.swing.GroupLayout pnlRunner3Layout = new javax.swing.GroupLayout(pnlRunner3);
        pnlRunner3.setLayout(pnlRunner3Layout);
        pnlRunner3Layout.setHorizontalGroup(
            pnlRunner3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunner3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunner3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTempo3)
                .addContainerGap())
        );
        pnlRunner3Layout.setVerticalGroup(
            pnlRunner3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunner3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlRunner3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunner3)
                    .addComponent(lblTempo3))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnlBase.add(pnlRunner3);
        pnlRunner3.setBounds(397, 128, 122, 55);

        pnlRunner4.setBackground(new java.awt.Color(153, 204, 255));

        lblRunner4.setText("Runner 4");

        lblTempo4.setText("0");

        javax.swing.GroupLayout pnlRunner4Layout = new javax.swing.GroupLayout(pnlRunner4);
        pnlRunner4.setLayout(pnlRunner4Layout);
        pnlRunner4Layout.setHorizontalGroup(
            pnlRunner4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunner4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunner4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(lblTempo4)
                .addContainerGap())
        );
        pnlRunner4Layout.setVerticalGroup(
            pnlRunner4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunner4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlRunner4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunner4)
                    .addComponent(lblTempo4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBase.add(pnlRunner4);
        pnlRunner4.setBounds(397, 189, 122, 55);

        pnlRunner2.setBackground(new java.awt.Color(153, 204, 255));

        lblRunner2.setText("Runner 2");

        lblTempo2.setText("0");

        javax.swing.GroupLayout pnlRunner2Layout = new javax.swing.GroupLayout(pnlRunner2);
        pnlRunner2.setLayout(pnlRunner2Layout);
        pnlRunner2Layout.setHorizontalGroup(
            pnlRunner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunner2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunner2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTempo2)
                .addContainerGap())
        );
        pnlRunner2Layout.setVerticalGroup(
            pnlRunner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunner2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlRunner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunner2)
                    .addComponent(lblTempo2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBase.add(pnlRunner2);
        pnlRunner2.setBounds(397, 67, 122, 55);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmStaffetta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmStaffetta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmStaffetta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmStaffetta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmStaffetta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvvia;
    private javax.swing.JButton btnFerma;
    private javax.swing.JButton btnRiprendi;
    private javax.swing.JButton btnSospende;
    private javax.swing.JComboBox<String> cmbVelocita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblRunner1;
    private javax.swing.JLabel lblRunner2;
    private javax.swing.JLabel lblRunner3;
    private javax.swing.JLabel lblRunner4;
    private javax.swing.JLabel lblTempo1;
    private javax.swing.JLabel lblTempo2;
    private javax.swing.JLabel lblTempo3;
    private javax.swing.JLabel lblTempo4;
    private javax.swing.JProgressBar pgbRunner1;
    private javax.swing.JProgressBar pgbRunner2;
    private javax.swing.JProgressBar pgbRunner3;
    private javax.swing.JProgressBar pgbRunner4;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JPanel pnlRunner1;
    private javax.swing.JPanel pnlRunner2;
    private javax.swing.JPanel pnlRunner3;
    private javax.swing.JPanel pnlRunner4;
    // End of variables declaration//GEN-END:variables
}
