/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threadrelay;
import javax.swing.*; //import libreria java swing per immagine
import java.util.ArrayList;
/**
 *
 * @author martinelli.alessandr
 */
//Finestra grafica
//Listener interfaccia per comunicare tra GUI e thread
public class JFrmStaffetta extends javax.swing.JFrame implements Listener{

    ArrayList<Runner> partecipanti = new ArrayList<>(); //Lista dei corridori
    ArrayList<Thread> Thread = new ArrayList<>(); //Thread associati ai runners
    /**
     * Creates new form JFrmStaffetta
     */
    public JFrmStaffetta() { //Costruttore per inizializzare la GUI
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        cmbVelocita = new javax.swing.JComboBox<>();
        btnAvvia = new javax.swing.JButton();
        btnSospende = new javax.swing.JButton();
        btnFerma = new javax.swing.JButton();
        btnRiprendi = new javax.swing.JButton();
        pnlRunner1 = new javax.swing.JPanel();
        lblRunner1 = new javax.swing.JLabel();
        lblTempo1 = new javax.swing.JLabel();
        pnlRunner3 = new javax.swing.JPanel();
        lblRunner3 = new javax.swing.JLabel();
        lblTempo3 = new javax.swing.JLabel();
        pnlRunner4 = new javax.swing.JPanel();
        lblRunner4 = new javax.swing.JLabel();
        lblTempo4 = new javax.swing.JLabel();
        pnlRunner2 = new javax.swing.JPanel();
        lblRunner2 = new javax.swing.JLabel();
        lblTempo2 = new javax.swing.JLabel();
        pnl1 = new javax.swing.JPanel();
        lblThread2 = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        lblThread3 = new javax.swing.JLabel();
        pnl3 = new javax.swing.JPanel();
        lblThread4 = new javax.swing.JLabel();
        pnl4 = new javax.swing.JPanel();
        lblThread1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBase.setLayout(null);

        cmbVelocita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Slow", "Regular", "Fast" }));
        cmbVelocita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVelocitaActionPerformed(evt);
            }
        });
        pnlBase.add(cmbVelocita);
        cmbVelocita.setBounds(12, 250, 74, 22);

        btnAvvia.setText("Avvia");
        btnAvvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvviaActionPerformed(evt);
            }
        });
        pnlBase.add(btnAvvia);
        btnAvvia.setBounds(90, 250, 72, 23);

        btnSospende.setText("Sospendi");
        btnSospende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSospendeActionPerformed(evt);
            }
        });
        pnlBase.add(btnSospende);
        btnSospende.setBounds(170, 250, 80, 23);

        btnFerma.setText("Ferma");
        btnFerma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermaActionPerformed(evt);
            }
        });
        pnlBase.add(btnFerma);
        btnFerma.setBounds(260, 250, 72, 23);

        btnRiprendi.setText("Riprendi");
        btnRiprendi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiprendiActionPerformed(evt);
            }
        });
        pnlBase.add(btnRiprendi);
        btnRiprendi.setBounds(340, 250, 80, 23);

        pnlRunner1.setBackground(new java.awt.Color(153, 204, 255));

        lblRunner1.setText("Runner 1");

        lblTempo1.setText("0");

        javax.swing.GroupLayout pnlRunner1Layout = new javax.swing.GroupLayout(pnlRunner1);
        pnlRunner1.setLayout(pnlRunner1Layout);
        pnlRunner1Layout.setHorizontalGroup(
            pnlRunner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunner1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunner1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(lblTempo1)
                .addContainerGap())
        );
        pnlRunner1Layout.setVerticalGroup(
            pnlRunner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRunner1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRunner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunner1)
                    .addComponent(lblTempo1))
                .addGap(19, 19, 19))
        );

        pnlBase.add(pnlRunner1);
        pnlRunner1.setBounds(397, 6, 122, 55);

        pnlRunner3.setBackground(new java.awt.Color(153, 204, 255));

        lblRunner3.setText("Runner 3");

        lblTempo3.setText("0");

        javax.swing.GroupLayout pnlRunner3Layout = new javax.swing.GroupLayout(pnlRunner3);
        pnlRunner3.setLayout(pnlRunner3Layout);
        pnlRunner3Layout.setHorizontalGroup(
            pnlRunner3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunner3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunner3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTempo3)
                .addContainerGap())
        );
        pnlRunner3Layout.setVerticalGroup(
            pnlRunner3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunner3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlRunner3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunner3)
                    .addComponent(lblTempo3))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnlBase.add(pnlRunner3);
        pnlRunner3.setBounds(397, 128, 122, 55);

        pnlRunner4.setBackground(new java.awt.Color(153, 204, 255));

        lblRunner4.setText("Runner 4");

        lblTempo4.setText("0");

        javax.swing.GroupLayout pnlRunner4Layout = new javax.swing.GroupLayout(pnlRunner4);
        pnlRunner4.setLayout(pnlRunner4Layout);
        pnlRunner4Layout.setHorizontalGroup(
            pnlRunner4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunner4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunner4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(lblTempo4)
                .addContainerGap())
        );
        pnlRunner4Layout.setVerticalGroup(
            pnlRunner4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunner4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlRunner4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunner4)
                    .addComponent(lblTempo4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBase.add(pnlRunner4);
        pnlRunner4.setBounds(397, 189, 122, 55);

        pnlRunner2.setBackground(new java.awt.Color(153, 204, 255));

        lblRunner2.setText("Runner 2");

        lblTempo2.setText("0");

        javax.swing.GroupLayout pnlRunner2Layout = new javax.swing.GroupLayout(pnlRunner2);
        pnlRunner2.setLayout(pnlRunner2Layout);
        pnlRunner2Layout.setHorizontalGroup(
            pnlRunner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunner2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunner2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTempo2)
                .addContainerGap())
        );
        pnlRunner2Layout.setVerticalGroup(
            pnlRunner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunner2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlRunner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunner2)
                    .addComponent(lblTempo2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBase.add(pnlRunner2);
        pnlRunner2.setBounds(397, 67, 122, 55);

        pnl1.setBackground(new java.awt.Color(204, 204, 204));

        lblThread2.setText("🏃‍");

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThread2)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblThread2)
                .addContainerGap())
        );

        pnlBase.add(pnl1);
        pnl1.setBounds(10, 20, 370, 40);

        pnl2.setBackground(new java.awt.Color(204, 204, 204));

        lblThread3.setText("🏃‍");

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThread3)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblThread3)
                .addContainerGap())
        );

        pnlBase.add(pnl2);
        pnl2.setBounds(10, 80, 370, 40);

        pnl3.setBackground(new java.awt.Color(204, 204, 204));

        lblThread4.setText("🏃‍");

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThread4)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblThread4)
                .addContainerGap())
        );

        pnlBase.add(pnl3);
        pnl3.setBounds(10, 140, 370, 40);

        pnl4.setBackground(new java.awt.Color(204, 204, 204));

        lblThread1.setText("🏃‍");

        javax.swing.GroupLayout pnl4Layout = new javax.swing.GroupLayout(pnl4);
        pnl4.setLayout(pnl4Layout);
        pnl4Layout.setHorizontalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThread1)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        pnl4Layout.setVerticalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblThread1)
                .addContainerGap())
        );

        pnlBase.add(pnl4);
        pnl4.setBounds(10, 200, 370, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBase, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBase, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbVelocitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVelocitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVelocitaActionPerformed

    private void btnAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaActionPerformed
        //Vario la velocità 
        //La scelgo nella combo box.
        int velocita = 0;
        if (cmbVelocita.getSelectedItem()=="Slow"){
            velocita = 90;
        }
        else if (cmbVelocita.getSelectedItem()=="Regular"){
            velocita = 50;
        }
        else if (cmbVelocita.getSelectedItem()=="Fast"){
            velocita = 10;
        }
        //Creo i thread
        for (int i=1; i<5; i++){
            Runner r = new Runner(velocita, i, this);
            Thread t = new Thread(r);
            partecipanti.add(r);
            Thread.add(t);
        }
        Thread.get(0).start();
    }//GEN-LAST:event_btnAvviaActionPerformed

    private void btnSospendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSospendeActionPerformed
        //Ferma i thread
        for (int i=0; i<4; i++){
            partecipanti.get(i).pausa();
        }
    }//GEN-LAST:event_btnSospendeActionPerformed

    private void btnFermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermaActionPerformed
         //Prende i runner e li ferma
         //Interrompe i thread
         //Pulisce tutto (svuotando la lista dei thread e di runners)
        for (int i=0; i<4; i++){
            partecipanti.get(i).ferma();
        }
          for (int i=0; i<4; i++){
            Thread.get(i).interrupt();
        }
          Thread.clear();
          partecipanti.clear();
    }//GEN-LAST:event_btnFermaActionPerformed

    private void btnRiprendiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiprendiActionPerformed
         //Fa riprendere i thread
        for (int i=0; i<4; i++){
            partecipanti.get(i).riprendi();
        }
    }//GEN-LAST:event_btnRiprendiActionPerformed
    //Mostra "Fine" nella label quando un Runner ha corso.
    //Se non ha finito (Else...) mostra il valore.
    public void aggiornaValori(int valore, int nRunner){
        if (nRunner==1){
            pgbRunner1.setValue(valore);
            if (valore==100){
             lblTempo1.setText("Fine");
            }
            else {
                lblTempo1.setText(String.valueOf(valore));
            }
        }
        else if (nRunner==2){
            pgbRunner2.setValue(valore);
        if (valore==100){
            lblTempo2.setText("Fine");
        }
        else {
            lblTempo2.setText(String.valueOf(valore));
        }
        }
        else if (nRunner==3){
            pgbRunner3.setValue(valore);
        if (valore==100){
            lblTempo3.setText("Fine");
        }
        else {
            lblTempo3.setText(String.valueOf(valore));
        }
        }
        else if (nRunner==4){
            pgbRunner4.setValue(valore);
            if(valore==100){
                lblTempo4.setText("Fine");
            }
            else {
                lblTempo4.setText(String.valueOf(valore));
            }
        }
    }
    //Controlla che il thread non è il quarto (Che non è l'ultimo)
    //Fa partire il thread successivo.
    public void prossimoThread(int nRunner){
        if (nRunner!=4){
            Thread.get(nRunner).start();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmStaffetta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmStaffetta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmStaffetta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmStaffetta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmStaffetta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvvia;
    private javax.swing.JButton btnFerma;
    private javax.swing.JButton btnRiprendi;
    private javax.swing.JButton btnSospende;
    private javax.swing.JComboBox<String> cmbVelocita;
    private javax.swing.JLabel lblRunner1;
    private javax.swing.JLabel lblRunner2;
    private javax.swing.JLabel lblRunner3;
    private javax.swing.JLabel lblRunner4;
    private javax.swing.JLabel lblTempo1;
    private javax.swing.JLabel lblTempo2;
    private javax.swing.JLabel lblTempo3;
    private javax.swing.JLabel lblTempo4;
    private javax.swing.JLabel lblThread1;
    private javax.swing.JLabel lblThread2;
    private javax.swing.JLabel lblThread3;
    private javax.swing.JLabel lblThread4;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnl4;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JPanel pnlRunner1;
    private javax.swing.JPanel pnlRunner2;
    private javax.swing.JPanel pnlRunner3;
    private javax.swing.JPanel pnlRunner4;
    // End of variables declaration//GEN-END:variables
}
